apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "petclinic.fullname" . }}
    component:  {{ .Values.Database.service.name }}
    {{- include "petclinic.labels" . | nindent 4 }}
  name:  {{ .Values.Database.service.name }}
spec:
  ports:
  - port:  {{ .Values.Database.service.port }}
    protocol:  {{ .Values.Database.service.protocol }}
    targetPort: {{ .Values.Database.service.port }}
  selector:
    component:  {{ .Values.Database.service.name }}
